from PyQt5.QtCore import Qt, pyqtSignal, QTimer, QRegExp, pyqtSlot, pyqtSignal
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QWidget, QLCDNumber, QSlider,
     QVBoxLayout, QApplication)
from PyQt5.QtGui import QIcon, QPixmap, QRegExpValidator
from PyQt5.QtWidgets import QApplication, QDialog, QLabel, QMessageBox

from openpyxl import Workbook
import mysql.connector
import os

import face_recognition
import cv2
import os
import datetime
import mysql.connector
import sys
import os

x=os.getcwd()
dir=x[:-4]
sys.path.append(str(dir))
import main
import datasetgenerator

myDatabase = mysql.connector.connect(
    host="localhost",
    user="root",
    passwd="123456",
    database="FRAS"
)

mycursor = myDatabase.cursor()


class Ui_FRAS(object):
    def setupUi(self, FRAS):
        FRAS.setObjectName("FRAS")
        FRAS.resize(800, 800)
        self.centralwidget = QtWidgets.QWidget(FRAS)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setAcceptDrops(False)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet("background-color: rgb(21, 155, 206);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.label = QtWidgets.QLabel(self.page1)
        self.label.setGeometry(QtCore.QRect(173, 410, 241, 21))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color:rgb(249, 199, 206)")
        self.label.setObjectName("label")
        self.userName_1 = QtWidgets.QLineEdit(self.page1)
        self.userName_1.setEnabled(True)
        self.userName_1.setGeometry(QtCore.QRect(420, 403, 321, 31))
        self.userName_1.setAutoFillBackground(False)
        self.userName_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.userName_1.setObjectName("userName_1")
        self.label_2 = QtWidgets.QLabel(self.page1)
        self.label_2.setGeometry(QtCore.QRect(173, 440, 231, 20))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("color:rgb(249, 199, 206)")
        self.label_2.setObjectName("label_2")
        self.password_1 = QtWidgets.QLineEdit(self.page1)
        self.password_1.setEnabled(True)
        self.password_1.setGeometry(QtCore.QRect(420, 439, 321, 31))
        self.password_1.setAutoFillBackground(False)
        self.password_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password_1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_1.setObjectName("password_1")
        self.logIn = QtWidgets.QPushButton(self.page1)
        self.logIn.setGeometry(QtCore.QRect(420, 480, 321, 31))
        self.logIn.setAutoFillBackground(False)
        self.logIn.setStyleSheet("background-color: rgb(21, 155, 206);\n"
"color: rgb(249, 199, 206);")
        self.logIn.setObjectName("logIn")
        self.label_4 = QtWidgets.QLabel(self.page1)
        self.label_4.setGeometry(QtCore.QRect(970, 750, 73, 16))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.page1)
        self.label_3.setGeometry(QtCore.QRect(240, 90, 551, 201))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("border-image: url(:/newPrefix/b.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.signup = QtWidgets.QPushButton(self.page1)
        self.signup.setGeometry(QtCore.QRect(40, 710, 131, 31))
        self.signup.setStyleSheet("color: rgb(249, 199, 206);")
        self.signup.setObjectName("signup")
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.textBrowser = QtWidgets.QTextBrowser(self.page2)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 231, 101))
        self.textBrowser.setStyleSheet("border-image: url(:/newPrefix/b.png);")
        self.textBrowser.setObjectName("textBrowser")
        self.logOut = QtWidgets.QPushButton(self.page2)
        self.logOut.setGeometry(QtCore.QRect(840, 680, 201, 51))
        self.logOut.setObjectName("logOut")
        self.stopProg_1 = QtWidgets.QPushButton(self.page2)
        self.stopProg_1.setGeometry(QtCore.QRect(50, 680, 201, 51))
        self.stopProg_1.setObjectName("stopProg_1")
        self.label_58 = QtWidgets.QLabel(self.page2)
        self.label_58.setGeometry(QtCore.QRect(360, 70, 371, 81))
        self.label_58.setObjectName("label_58")
        self.runProg = QtWidgets.QPushButton(self.page2)
        self.runProg.setGeometry(QtCore.QRect(180, 280, 371, 100))
        self.runProg.setMinimumSize(QtCore.QSize(50, 100))
        self.runProg.setStyleSheet("color:rgb(249, 199, 206)")
        self.runProg.setObjectName("runProg")
        self.log = QtWidgets.QPushButton(self.page2)
        self.log.setGeometry(QtCore.QRect(314, 410, 461, 100))
        self.log.setMinimumSize(QtCore.QSize(50, 100))
        self.log.setStyleSheet("color:rgb(249, 199, 206)")
        self.log.setObjectName("log")
        self.addNew = QtWidgets.QPushButton(self.page2)
        self.addNew.setGeometry(QtCore.QRect(570, 280, 371, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addNew.sizePolicy().hasHeightForWidth())
        self.addNew.setSizePolicy(sizePolicy)
        self.addNew.setMinimumSize(QtCore.QSize(50, 100))
        self.addNew.setStyleSheet("color:rgb(249, 199, 206)")
        self.addNew.setObjectName("addNew")
        self.stackedWidget.addWidget(self.page2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.page_4)
        self.textBrowser_3.setGeometry(QtCore.QRect(0, 0, 191, 91))
        self.textBrowser_3.setStyleSheet("border-image: url(:/newPrefix/b.png);")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.nameAdd = QtWidgets.QLineEdit(self.page_4)
        self.nameAdd.setEnabled(True)
        self.nameAdd.setGeometry(QtCore.QRect(450, 280, 261, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameAdd.sizePolicy().hasHeightForWidth())
        self.nameAdd.setSizePolicy(sizePolicy)
        self.nameAdd.setAutoFillBackground(False)
        self.nameAdd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nameAdd.setObjectName("nameAdd")
        self.idAdd = QtWidgets.QLineEdit(self.page_4)
        self.idAdd.setEnabled(True)
        self.idAdd.setGeometry(QtCore.QRect(450, 354, 261, 31))
        self.idAdd.setAutoFillBackground(False)
        self.idAdd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.idAdd.setObjectName("idAdd")
        self.emailAdd = QtWidgets.QLineEdit(self.page_4)
        self.emailAdd.setEnabled(True)
        self.emailAdd.setGeometry(QtCore.QRect(450, 430, 261, 31))
        self.emailAdd.setAutoFillBackground(False)
        self.emailAdd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.emailAdd.setObjectName("emailAdd")
        self.label_8 = QtWidgets.QLabel(self.page_4)
        self.label_8.setGeometry(QtCore.QRect(300, 30, 511, 161))
        self.label_8.setObjectName("label_8")
        self.layoutWidget = QtWidgets.QWidget(self.page_4)
        self.layoutWidget.setGeometry(QtCore.QRect(310, 260, 113, 221))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.cancel_4 = QtWidgets.QPushButton(self.page_4)
        self.cancel_4.setGeometry(QtCore.QRect(46, 720, 111, 31))
        self.cancel_4.setObjectName("cancel_4")
        self.ok_4 = QtWidgets.QPushButton(self.page_4)
        self.ok_4.setGeometry(QtCore.QRect(900, 720, 131, 31))
        self.ok_4.setObjectName("ok_4")
        self.newPhoto = QtWidgets.QLabel(self.page_4)
        self.newPhoto.setGeometry(QtCore.QRect(450, 500, 261, 41))
        self.newPhoto.setText("")
        self.newPhoto.setObjectName("newPhoto")
        self.photoAdd = QtWidgets.QPushButton(self.page_4)
        self.photoAdd.setGeometry(QtCore.QRect(310, 510, 111, 31))
        self.photoAdd.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.photoAdd.setObjectName("photoAdd")
        self.stackedWidget.addWidget(self.page_4)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.back_6 = QtWidgets.QPushButton(self.page_6)
        self.back_6.setGeometry(QtCore.QRect(20, 730, 121, 31))
        self.back_6.setObjectName("back_6")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.page_6)
        self.textBrowser_6.setGeometry(QtCore.QRect(0, 0, 231, 111))
        self.textBrowser_6.setStyleSheet("border-image: url(:/newPrefix/b.png);")
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.label_13 = QtWidgets.QLabel(self.page_6)
        self.label_13.setGeometry(QtCore.QRect(330, 110, 411, 101))
        self.label_13.setObjectName("label_13")
        self.label_17 = QtWidgets.QLabel(self.page_6)
        self.label_17.setGeometry(QtCore.QRect(60, 255, 121, 51))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.page_6)
        self.label_18.setGeometry(QtCore.QRect(70, 320, 54, 20))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.page_6)
        self.label_19.setGeometry(QtCore.QRect(70, 360, 54, 20))
        self.label_19.setObjectName("label_19")
        self.fromDay = QtWidgets.QComboBox(self.page_6)
        self.fromDay.setGeometry(QtCore.QRect(200, 320, 61, 22))
        self.fromDay.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fromDay.setInputMethodHints(QtCore.Qt.ImhNone)
        self.fromDay.setObjectName("fromDay")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.fromDay.addItem("")
        self.label_20 = QtWidgets.QLabel(self.page_6)
        self.label_20.setGeometry(QtCore.QRect(140, 320, 54, 20))
        self.label_20.setObjectName("label_20")
        self.label_25 = QtWidgets.QLabel(self.page_6)
        self.label_25.setGeometry(QtCore.QRect(290, 320, 54, 20))
        self.label_25.setObjectName("label_25")
        self.toDay = QtWidgets.QComboBox(self.page_6)
        self.toDay.setGeometry(QtCore.QRect(200, 360, 61, 22))
        self.toDay.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.toDay.setObjectName("toDay")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.toDay.addItem("")
        self.fromMonth = QtWidgets.QComboBox(self.page_6)
        self.fromMonth.setGeometry(QtCore.QRect(360, 320, 61, 22))
        self.fromMonth.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fromMonth.setInputMethodHints(QtCore.Qt.ImhNone)
        self.fromMonth.setObjectName("fromMonth")
        self.fromMonth.addItem("")
        self.fromMonth.addItem("")
        self.fromMonth.addItem("")
        self.fromMonth.addItem("")
        self.fromMonth.addItem("")
        self.fromMonth.addItem("")
        self.fromMonth.addItem("")
        self.fromMonth.addItem("")
        self.fromMonth.addItem("")
        self.fromMonth.addItem("")
        self.fromMonth.addItem("")
        self.fromMonth.addItem("")
        self.label_26 = QtWidgets.QLabel(self.page_6)
        self.label_26.setGeometry(QtCore.QRect(290, 360, 54, 20))
        self.label_26.setObjectName("label_26")
        self.toMonth = QtWidgets.QComboBox(self.page_6)
        self.toMonth.setGeometry(QtCore.QRect(360, 360, 61, 22))
        self.toMonth.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.toMonth.setObjectName("toMonth")
        self.toMonth.addItem("")
        self.toMonth.addItem("")
        self.toMonth.addItem("")
        self.toMonth.addItem("")
        self.toMonth.addItem("")
        self.toMonth.addItem("")
        self.toMonth.addItem("")
        self.toMonth.addItem("")
        self.toMonth.addItem("")
        self.toMonth.addItem("")
        self.toMonth.addItem("")
        self.toMonth.addItem("")
        self.label_27 = QtWidgets.QLabel(self.page_6)
        self.label_27.setGeometry(QtCore.QRect(140, 360, 54, 20))
        self.label_27.setObjectName("label_27")
        self.label_55 = QtWidgets.QLabel(self.page_6)
        self.label_55.setGeometry(QtCore.QRect(450, 320, 54, 20))
        self.label_55.setObjectName("label_55")
        self.fromYear = QtWidgets.QComboBox(self.page_6)
        self.fromYear.setGeometry(QtCore.QRect(520, 320, 61, 22))
        self.fromYear.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fromYear.setObjectName("fromYear")
        self.fromYear.addItem("")
        self.fromYear.addItem("")
        self.fromYear.addItem("")
        self.fromYear.addItem("")
        self.fromYear.addItem("")
        self.fromYear.addItem("")
        self.fromYear.addItem("")
        self.fromYear.addItem("")
        self.fromYear.addItem("")
        self.fromYear.addItem("")
        self.fromYear.addItem("")
        self.fromYear.addItem("")
        self.fromYear.addItem("")
        self.fromYear.addItem("")
        self.toYear = QtWidgets.QComboBox(self.page_6)
        self.toYear.setGeometry(QtCore.QRect(520, 360, 61, 22))
        self.toYear.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.toYear.setObjectName("toYear")
        self.toYear.addItem("")
        self.toYear.addItem("")
        self.toYear.addItem("")
        self.toYear.addItem("")
        self.toYear.addItem("")
        self.toYear.addItem("")
        self.toYear.addItem("")
        self.toYear.addItem("")
        self.toYear.addItem("")
        self.toYear.addItem("")
        self.toYear.addItem("")
        self.toYear.addItem("")
        self.toYear.addItem("")
        self.toYear.addItem("")
        self.label_56 = QtWidgets.QLabel(self.page_6)
        self.label_56.setGeometry(QtCore.QRect(450, 360, 54, 20))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.page_6)
        self.label_57.setGeometry(QtCore.QRect(70, 480, 54, 21))
        self.label_57.setObjectName("label_57")
        self.logId = QtWidgets.QLineEdit(self.page_6)
        self.logId.setGeometry(QtCore.QRect(120, 480, 171, 21))
        self.logId.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.logId.setObjectName("logId")
        self.submitLog = QtWidgets.QPushButton(self.page_6)
        self.submitLog.setGeometry(QtCore.QRect(900, 730, 121, 31))
        self.submitLog.setAutoDefault(False)
        self.submitLog.setDefault(False)
        self.submitLog.setFlat(False)
        self.submitLog.setObjectName("submitLog")
        self.label_24 = QtWidgets.QLabel(self.page_6)
        self.label_24.setGeometry(QtCore.QRect(60, 410, 211, 51))
        self.label_24.setObjectName("label_24")
        self.stackedWidget.addWidget(self.page_6)
        self.page_1b = QtWidgets.QWidget()
        self.page_1b.setObjectName("page_1b")
        self.label_21 = QtWidgets.QLabel(self.page_1b)
        self.label_21.setGeometry(QtCore.QRect(360, 130, 371, 81))
        self.label_21.setObjectName("label_21")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.page_1b)
        self.textBrowser_5.setGeometry(QtCore.QRect(0, 0, 251, 111))
        self.textBrowser_5.setStyleSheet("border-image: url(:/newPrefix/b.png);")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.signup_1b = QtWidgets.QPushButton(self.page_1b)
        self.signup_1b.setGeometry(QtCore.QRect(860, 700, 141, 41))
        self.signup_1b.setAutoFillBackground(False)
        self.signup_1b.setStyleSheet("background-color: rgb(21, 155, 206);\n"
"")
        self.signup_1b.setObjectName("signup_1b")
        self.cancel_1b = QtWidgets.QPushButton(self.page_1b)
        self.cancel_1b.setGeometry(QtCore.QRect(50, 700, 141, 41))
        self.cancel_1b.setObjectName("cancel_1b")
        self.splitter_2 = QtWidgets.QSplitter(self.page_1b)
        self.splitter_2.setGeometry(QtCore.QRect(190, 320, 241, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label_23 = QtWidgets.QLabel(self.splitter_2)
        self.label_23.setAutoFillBackground(False)
        self.label_23.setStyleSheet("color:rgb(249, 199, 206)")
        self.label_23.setObjectName("label_23")
        self.label_22 = QtWidgets.QLabel(self.splitter_2)
        self.label_22.setAutoFillBackground(False)
        self.label_22.setStyleSheet("color:rgb(249, 199, 206)")
        self.label_22.setObjectName("label_22")
        self.splitter = QtWidgets.QSplitter(self.page_1b)
        self.splitter.setGeometry(QtCore.QRect(430, 320, 281, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.userName_1b = QtWidgets.QLineEdit(self.splitter)
        self.userName_1b.setEnabled(True)
        self.userName_1b.setAutoFillBackground(False)
        self.userName_1b.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.userName_1b.setObjectName("userName_1b")
        self.password_1b = QtWidgets.QLineEdit(self.splitter)
        self.password_1b.setEnabled(True)
        self.password_1b.setAutoFillBackground(False)
        self.password_1b.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password_1b.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_1b.setObjectName("password_1b")
        self.stackedWidget.addWidget(self.page_1b)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        FRAS.setCentralWidget(self.centralwidget)

        self.retranslateUi(FRAS)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FRAS)
        FRAS.setTabOrder(self.fromDay, self.fromMonth)
        FRAS.setTabOrder(self.fromMonth, self.fromYear)
        FRAS.setTabOrder(self.fromYear, self.toDay)
        FRAS.setTabOrder(self.toDay, self.toMonth)
        FRAS.setTabOrder(self.toMonth, self.toYear)
        FRAS.setTabOrder(self.toYear, self.logId)
        FRAS.setTabOrder(self.logId, self.userName_1)
        FRAS.setTabOrder(self.userName_1, self.password_1)
        FRAS.setTabOrder(self.password_1, self.logIn)
        FRAS.setTabOrder(self.logIn, self.nameAdd)
        FRAS.setTabOrder(self.nameAdd, self.idAdd)
        FRAS.setTabOrder(self.idAdd, self.emailAdd)
        FRAS.setTabOrder(self.emailAdd, self.cancel_4)
        FRAS.setTabOrder(self.cancel_4, self.runProg)
        FRAS.setTabOrder(self.runProg, self.ok_4)
        FRAS.setTabOrder(self.ok_4, self.back_6)
        FRAS.setTabOrder(self.back_6, self.textBrowser_5)
        FRAS.setTabOrder(self.textBrowser_5, self.signup_1b)
        FRAS.setTabOrder(self.signup_1b, self.cancel_1b)
        FRAS.setTabOrder(self.cancel_1b, self.userName_1b)
        FRAS.setTabOrder(self.userName_1b, self.password_1b)
        FRAS.setTabOrder(self.password_1b, self.textBrowser_6)
        FRAS.setTabOrder(self.textBrowser_6, self.stopProg_1)
        FRAS.setTabOrder(self.stopProg_1, self.addNew)
        FRAS.setTabOrder(self.addNew, self.signup)
        FRAS.setTabOrder(self.signup, self.textBrowser_3)
        FRAS.setTabOrder(self.textBrowser_3, self.textBrowser)
        FRAS.setTabOrder(self.textBrowser, self.logOut)
        FRAS.setTabOrder(self.logOut, self.submitLog)

#adding new employee information from addEmp function

        self.ok_4.clicked.connect(self.addEmp)

# pressing submit button
        self.submitLog.clicked.connect(self.logGen)

#calling signUp function

        self.signup_1b.clicked.connect(self.signUp)

# calling Login function
        self.logIn.clicked.connect(self.Login)

# calling goPage1 fuction to make push button go to page 1
        self.logOut.clicked.connect(self.goPage1)
        self.cancel_1b.clicked.connect(self.goPage1)

# calling goPage2 fuction to make push button go to page 2

        self.cancel_4.clicked.connect(self.goPage2)
        self.ok_4.clicked.connect(self.addEmp)
        self.back_6.clicked.connect(self.goPage2)

# calling goPage3 fuction to make push button go to page 4
        self.addNew.clicked.connect(self.goPage4)
        self.runProg.clicked.connect(self.OpenCam)
        self.photoAdd.clicked.connect(self.NewUser)
# calling goPage3 fuction to make push button go to page 6
        self.log.clicked.connect(self.goPage6)

#calling goSignUp function to make push button go to sign up page
        self.signup.clicked.connect(self.goSignUp)


    def retranslateUi(self, FRAS):
        _translate = QtCore.QCoreApplication.translate
        FRAS.setWindowTitle(_translate("FRAS", "MainWindow"))
        self.label.setText(_translate("FRAS", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">User Name</span></p></body></html>"))
        self.userName_1.setWhatsThis(_translate("FRAS", "<html><head/><body><p><br/></p></body></html>"))
        self.label_2.setText(_translate("FRAS", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Password</span></p></body></html>"))
        self.logIn.setText(_translate("FRAS", "Log In"))
        self.label_4.setText(_translate("FRAS", "Version 1.0.0"))
        self.signup.setText(_translate("FRAS", "Sign up"))
        self.logOut.setText(_translate("FRAS", "Log out"))
        self.stopProg_1.setText(_translate("FRAS", "Stop Program"))
        self.label_58.setText(_translate("FRAS", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600;\">Main Menu</span></p></body></html>"))
        self.runProg.setText(_translate("FRAS", "Start"))
        self.log.setText(_translate("FRAS", "Log"))
        self.addNew.setText(_translate("FRAS", "Add New Employee"))
        self.nameAdd.setWhatsThis(_translate("FRAS", "<html><head/><body><p><br/></p></body></html>"))
        self.idAdd.setWhatsThis(_translate("FRAS", "<html><head/><body><p><br/></p></body></html>"))
        self.emailAdd.setWhatsThis(_translate("FRAS", "<html><head/><body><p><br/></p></body></html>"))
        self.label_8.setText(_translate("FRAS", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Add New Employee Information</span></p></body></html>"))
        self.label_6.setText(_translate("FRAS", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Name :</span></p></body></html>"))
        self.label_7.setText(_translate("FRAS", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">ID number :</span></p></body></html>"))
        self.label_9.setText(_translate("FRAS", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Email :</span></p></body></html>"))
        self.cancel_4.setText(_translate("FRAS", "Cancel"))
        self.ok_4.setText(_translate("FRAS", "OK"))
        self.photoAdd.setText(_translate("FRAS", "Add Photo"))
        self.back_6.setText(_translate("FRAS", "Back"))
        self.label_13.setText(_translate("FRAS", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600;\">LOG</span></p></body></html>"))
        self.label_17.setText(_translate("FRAS", "<html><head/><body><p><span style=\" font-size:14pt;\">Select Date:</span></p></body></html>"))
        self.label_18.setText(_translate("FRAS", "<html><head/><body><p><span style=\" font-size:10pt;\">From:</span></p></body></html>"))
        self.label_19.setText(_translate("FRAS", "<html><head/><body><p><span style=\" font-size:10pt;\">To:</span></p></body></html>"))
        self.fromDay.setItemText(0, _translate("FRAS", "01"))
        self.fromDay.setItemText(1, _translate("FRAS", "02"))
        self.fromDay.setItemText(2, _translate("FRAS", "03"))
        self.fromDay.setItemText(3, _translate("FRAS", "04"))
        self.fromDay.setItemText(4, _translate("FRAS", "05"))
        self.fromDay.setItemText(5, _translate("FRAS", "06"))
        self.fromDay.setItemText(6, _translate("FRAS", "07"))
        self.fromDay.setItemText(7, _translate("FRAS", "08"))
        self.fromDay.setItemText(8, _translate("FRAS", "09"))
        self.fromDay.setItemText(9, _translate("FRAS", "10"))
        self.fromDay.setItemText(10, _translate("FRAS", "11"))
        self.fromDay.setItemText(11, _translate("FRAS", "12"))
        self.fromDay.setItemText(12, _translate("FRAS", "13"))
        self.fromDay.setItemText(13, _translate("FRAS", "14"))
        self.fromDay.setItemText(14, _translate("FRAS", "15"))
        self.fromDay.setItemText(15, _translate("FRAS", "16"))
        self.fromDay.setItemText(16, _translate("FRAS", "17"))
        self.fromDay.setItemText(17, _translate("FRAS", "18"))
        self.fromDay.setItemText(18, _translate("FRAS", "19"))
        self.fromDay.setItemText(19, _translate("FRAS", "20"))
        self.fromDay.setItemText(20, _translate("FRAS", "21"))
        self.fromDay.setItemText(21, _translate("FRAS", "22"))
        self.fromDay.setItemText(22, _translate("FRAS", "23"))
        self.fromDay.setItemText(23, _translate("FRAS", "24"))
        self.fromDay.setItemText(24, _translate("FRAS", "25"))
        self.fromDay.setItemText(25, _translate("FRAS", "26"))
        self.fromDay.setItemText(26, _translate("FRAS", "27"))
        self.fromDay.setItemText(27, _translate("FRAS", "28"))
        self.fromDay.setItemText(28, _translate("FRAS", "29"))
        self.fromDay.setItemText(29, _translate("FRAS", "30"))
        self.fromDay.setItemText(30, _translate("FRAS", "31"))
        self.label_20.setText(_translate("FRAS", "<html><head/><body><p><span style=\" font-size:10pt;\">Day</span></p></body></html>"))
        self.label_25.setText(_translate("FRAS", "<html><head/><body><p><span style=\" font-size:10pt;\">Month</span></p></body></html>"))
        self.toDay.setItemText(0, _translate("FRAS", "01"))
        self.toDay.setItemText(1, _translate("FRAS", "02"))
        self.toDay.setItemText(2, _translate("FRAS", "03"))
        self.toDay.setItemText(3, _translate("FRAS", "04"))
        self.toDay.setItemText(4, _translate("FRAS", "05"))
        self.toDay.setItemText(5, _translate("FRAS", "06"))
        self.toDay.setItemText(6, _translate("FRAS", "07"))
        self.toDay.setItemText(7, _translate("FRAS", "08"))
        self.toDay.setItemText(8, _translate("FRAS", "09"))
        self.toDay.setItemText(9, _translate("FRAS", "10"))
        self.toDay.setItemText(10, _translate("FRAS", "11"))
        self.toDay.setItemText(11, _translate("FRAS", "12"))
        self.toDay.setItemText(12, _translate("FRAS", "13"))
        self.toDay.setItemText(13, _translate("FRAS", "14"))
        self.toDay.setItemText(14, _translate("FRAS", "15"))
        self.toDay.setItemText(15, _translate("FRAS", "16"))
        self.toDay.setItemText(16, _translate("FRAS", "17"))
        self.toDay.setItemText(17, _translate("FRAS", "18"))
        self.toDay.setItemText(18, _translate("FRAS", "19"))
        self.toDay.setItemText(19, _translate("FRAS", "20"))
        self.toDay.setItemText(20, _translate("FRAS", "21"))
        self.toDay.setItemText(21, _translate("FRAS", "22"))
        self.toDay.setItemText(22, _translate("FRAS", "23"))
        self.toDay.setItemText(23, _translate("FRAS", "24"))
        self.toDay.setItemText(24, _translate("FRAS", "25"))
        self.toDay.setItemText(25, _translate("FRAS", "26"))
        self.toDay.setItemText(26, _translate("FRAS", "27"))
        self.toDay.setItemText(27, _translate("FRAS", "28"))
        self.toDay.setItemText(28, _translate("FRAS", "29"))
        self.toDay.setItemText(29, _translate("FRAS", "30"))
        self.toDay.setItemText(30, _translate("FRAS", "31"))
        self.fromMonth.setItemText(0, _translate("FRAS", "01"))
        self.fromMonth.setItemText(1, _translate("FRAS", "02"))
        self.fromMonth.setItemText(2, _translate("FRAS", "03"))
        self.fromMonth.setItemText(3, _translate("FRAS", "04"))
        self.fromMonth.setItemText(4, _translate("FRAS", "05"))
        self.fromMonth.setItemText(5, _translate("FRAS", "06"))
        self.fromMonth.setItemText(6, _translate("FRAS", "07"))
        self.fromMonth.setItemText(7, _translate("FRAS", "08"))
        self.fromMonth.setItemText(8, _translate("FRAS", "09"))
        self.fromMonth.setItemText(9, _translate("FRAS", "10"))
        self.fromMonth.setItemText(10, _translate("FRAS", "11"))
        self.fromMonth.setItemText(11, _translate("FRAS", "12"))
        self.label_26.setText(_translate("FRAS", "<html><head/><body><p><span style=\" font-size:10pt;\">Month</span></p></body></html>"))
        self.toMonth.setItemText(0, _translate("FRAS", "01"))
        self.toMonth.setItemText(1, _translate("FRAS", "02"))
        self.toMonth.setItemText(2, _translate("FRAS", "03"))
        self.toMonth.setItemText(3, _translate("FRAS", "04"))
        self.toMonth.setItemText(4, _translate("FRAS", "05"))
        self.toMonth.setItemText(5, _translate("FRAS", "06"))
        self.toMonth.setItemText(6, _translate("FRAS", "07"))
        self.toMonth.setItemText(7, _translate("FRAS", "08"))
        self.toMonth.setItemText(8, _translate("FRAS", "09"))
        self.toMonth.setItemText(9, _translate("FRAS", "10"))
        self.toMonth.setItemText(10, _translate("FRAS", "11"))
        self.toMonth.setItemText(11, _translate("FRAS", "12"))
        self.label_27.setText(_translate("FRAS", "<html><head/><body><p><span style=\" font-size:10pt;\">Day</span></p></body></html>"))
        self.label_55.setText(_translate("FRAS", "<html><head/><body><p><span style=\" font-size:10pt;\">Year</span></p></body></html>"))
        self.fromYear.setItemText(0, _translate("FRAS", "2010"))
        self.fromYear.setItemText(1, _translate("FRAS", "2011"))
        self.fromYear.setItemText(2, _translate("FRAS", "2012"))
        self.fromYear.setItemText(3, _translate("FRAS", "2013"))
        self.fromYear.setItemText(4, _translate("FRAS", "2014"))
        self.fromYear.setItemText(5, _translate("FRAS", "2015"))
        self.fromYear.setItemText(6, _translate("FRAS", "2016"))
        self.fromYear.setItemText(7, _translate("FRAS", "2017"))
        self.fromYear.setItemText(8, _translate("FRAS", "2018"))
        self.fromYear.setItemText(9, _translate("FRAS", "2019"))
        self.fromYear.setItemText(10, _translate("FRAS", "2020"))
        self.fromYear.setItemText(11, _translate("FRAS", "2021"))
        self.fromYear.setItemText(12, _translate("FRAS", "2022"))
        self.fromYear.setItemText(13, _translate("FRAS", "2023"))
        self.toYear.setItemText(0, _translate("FRAS", "2010"))
        self.toYear.setItemText(1, _translate("FRAS", "2011"))
        self.toYear.setItemText(2, _translate("FRAS", "2012"))
        self.toYear.setItemText(3, _translate("FRAS", "2013"))
        self.toYear.setItemText(4, _translate("FRAS", "2014"))
        self.toYear.setItemText(5, _translate("FRAS", "2015"))
        self.toYear.setItemText(6, _translate("FRAS", "2016"))
        self.toYear.setItemText(7, _translate("FRAS", "2017"))
        self.toYear.setItemText(8, _translate("FRAS", "2018"))
        self.toYear.setItemText(9, _translate("FRAS", "2019"))
        self.toYear.setItemText(10, _translate("FRAS", "2020"))
        self.toYear.setItemText(11, _translate("FRAS", "2021"))
        self.toYear.setItemText(12, _translate("FRAS", "2022"))
        self.toYear.setItemText(13, _translate("FRAS", "2023"))
        self.label_56.setText(_translate("FRAS", "<html><head/><body><p><span style=\" font-size:10pt;\">Year</span></p></body></html>"))
        self.label_57.setText(_translate("FRAS", "<html><head/><body><p><span style=\" font-size:11pt;\">ID:</span></p></body></html>"))
        self.submitLog.setText(_translate("FRAS", "Submit"))
        self.label_24.setText(_translate("FRAS", "<html><head/><body><p><span style=\" font-size:14pt;\">Select Employee:</span></p></body></html>"))
        self.label_21.setText(_translate("FRAS", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Adminstrator Sign Up</span></p></body></html>"))
        self.signup_1b.setText(_translate("FRAS", "Sign UP"))
        self.cancel_1b.setText(_translate("FRAS", "Cancel"))
        self.label_23.setText(_translate("FRAS", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">New User Name</span></p></body></html>"))
        self.label_22.setText(_translate("FRAS", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">New Password</span></p></body></html>"))
        self.userName_1b.setWhatsThis(_translate("FRAS", "<html><head/><body><p><br/></p></body></html>"))

#functions to change stacked widget index
    def goPage1(self):
        self.stackedWidget.setCurrentIndex(0)

    def goPage2(self):
        self.stackedWidget.setCurrentIndex(1)

    def goPage4(self):
        self.stackedWidget.setCurrentIndex(2)

    def goPage6(self):
        self.stackedWidget.setCurrentIndex(3)

    def goSignUp(self):
        self.stackedWidget.setCurrentIndex(4)


    def OpenCam(self):
        main.main()

    def NewUser(self):
        datasetgenerator.main()

# get the input
    def Login(self):
        user = self.userName_1.text()
        password = self.password_1.text()
        if  len(user) == 0 or len(password) == 0 :

            mb = QMessageBox()
            mb.setIcon(QMessageBox.Information)
            mb.setWindowTitle('Try Again')
            mb.setText('Username or Password is Wrong')
            mb.setStandardButtons(QMessageBox.Ok)
            mb.exec_()
            return

        else :
            sql = "SELECT * FROM HR WHERE ID = %s AND Password = %s"
            val = (user, password)
            mycursor.execute(sql,val)
            result = mycursor.fetchall()
            if len(result) :
                self.stackedWidget.setCurrentIndex(1) # change page
                self.userName_1.clear()
                self.password_1.clear()
            else :

                mb = QMessageBox()
                mb.setIcon(QMessageBox.Information)
                mb.setWindowTitle('Try Again')
                mb.setText('Username or Password is Wrong')
                mb.setStandardButtons(QMessageBox.Ok)
                mb.exec_()
                return



    def signUp(self):
        user1 = self.userName_1b.text()
        password1 = self.password_1b.text()
        if  len(user1) == 0 or len(password1) == 0 :

            mb = QMessageBox()
            mb.setIcon(QMessageBox.Information)
            mb.setWindowTitle('Try Again')
            mb.setText('Please fill all the blanks')
            mb.setStandardButtons(QMessageBox.Ok)
            mb.exec_()
            return

        else :
            val = (user1, password1)
            sql = "INSERT INTO HR (ID, Password) VALUES (%s, %s)"
            mycursor.execute(sql,val)
            myDatabase.commit()
            print(user1 + " is registered ")
            print('user:', user1)
            self.stackedWidget.setCurrentIndex(0) # change page
        self.userName_1b.clear()
        self.password_1b.clear()

    def addEmp(self):
        name = self.nameAdd.text()
        Id = self.idAdd.text()
        email = self.emailAdd.text()
        if len(name) == 0 or len(Id) == 0 or len(email) == 0:

            mb = QMessageBox()
            mb.setIcon(QMessageBox.Information)
            mb.setWindowTitle('Try Again')
            mb.setText('Username or Password is Wrong')
            mb.setStandardButtons(QMessageBox.Ok)
            mb.exec_()
            return

        else :
            val = (Id, name, email)
            sql = "INSERT INTO Employee (ID, Name, Email) VALUES (%s, %s, %s)"
            mycursor.execute(sql,val)
            myDatabase.commit()
            print(name + " is registered ")
            self.stackedWidget.setCurrentIndex(1) # change page
        self.nameAdd.clear()
        self.idAdd.clear()
        self.emailAdd.clear()


    def logGen(self):
        day1 = self.fromDay.currentText()
        month1 = self.fromMonth.currentText()
        year1 = self.fromYear.currentText()
        day2 = self.toDay.currentText()
        month2 = self.toMonth.currentText()
        year2 = self.toYear.currentText()
        Id_no=self.logId.text()
        if len(Id_no) == 0:
            mb = QMessageBox()
            mb.setIcon(QMessageBox.Information)
            mb.setWindowTitle('Try Again')
            mb.setText('Enter the ID')
            mb.setStandardButtons(QMessageBox.Ok)
            mb.exec_()
            return
        else:

            From = year1+"-"+month1+"-"+day1
            To = year2+"-"+month2+"-"+day2

            sql = "SELECT * FROM Attendance WHERE ID = %s AND Check_Date between %s AND %s"
            val = (Id_no, From, To)
            mycursor.execute(sql,val)
            result = mycursor.fetchall()
            #for x in result:
                #print(x)
            if result:
                wb = Workbook() # Creating excel
                ws = wb.create_sheet(0)
                #  ws.title = employee
                ws.append(mycursor.column_names)
                for row in result:
                    ws.append(row)
                wb.save(Id_no + ".xlsx")

                path = "C:/Users/USER/Documents/IIUM/Level 3/Sem 2/IDP/IDP proj" # The folder path
                path = os.path.realpath(path)
                os.startfile(path)
            else:
                mb = QMessageBox()
                mb.setIcon(QMessageBox.Information)
                mb.setWindowTitle('Try Again')
                mb.setText('The ID doesnt exist')
                mb.setStandardButtons(QMessageBox.Ok)
                mb.exec_()
                return


        #print(From)
        #print(To)
        #print(Id_no)

        self.logId.clear()










import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FRAS = QtWidgets.QMainWindow()
    ui = Ui_FRAS()
    ui.setupUi(FRAS)
    FRAS.show()
    sys.exit(app.exec_())
